apiVersion: v1
kind: Service
metadata:
  name: config-demo
spec:
  selector:
    app: config-demo
  ports:
    - name: rest
      port: 30918
      protocol: TCP
      nodePort: 30918
      targetPort: 9092
    - name: rpc
      port: 9012
      protocol: TCP
      targetPort: 9012
  type: NodePort